#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace ECER.Utilities.DataverseSdk.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class EcerContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public EcerContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Application"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Application> ecer_ApplicationSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Application>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_AssessmentTrainingLocation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_AssessmentTrainingLocation> ecer_AssessmentTrainingLocationSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_AssessmentTrainingLocation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Authentication"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Authentication> ecer_AuthenticationSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Authentication>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Certificate"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Certificate> ecer_CertificateSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Certificate>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_CertificateConditions"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_CertificateConditions> ecer_CertificateConditionsSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_CertificateConditions>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_CertificateType"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_CertificateType> ecer_CertificateTypeSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_CertificateType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_certifications"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_certifications> ecer_certificationsSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_certifications>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_ChangeofInformation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_ChangeofInformation> ecer_ChangeofInformationSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_ChangeofInformation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_CharacterReference"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_CharacterReference> ecer_CharacterReferenceSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_CharacterReference>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Comment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Comment> ecer_CommentSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Comment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Communication"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Communication> ecer_CommunicationSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Communication>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_CommunicationLineItem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_CommunicationLineItem> ecer_CommunicationLineItemSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_CommunicationLineItem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_CompletedCourse"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_CompletedCourse> ecer_CompletedCourseSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_CompletedCourse>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Course"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Course> ecer_CourseSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Course>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_DenialReason"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_DenialReason> ecer_DenialReasonSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_DenialReason>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_GuardianReference"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_GuardianReference> ecer_GuardianReferenceSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_GuardianReference>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_IANTemplateContent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_IANTemplateContent> ecer_IANTemplateContentSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_IANTemplateContent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_PortalRole"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_PortalRole> ecer_PortalRoleSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_PortalRole>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_PortalUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_PortalUser> ecer_PortalUserSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_PortalUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_PortalUser_ecer_PortalRole"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_PortalUser_ecer_PortalRole> ecer_PortalUser_ecer_PortalRoleSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_PortalUser_ecer_PortalRole>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_PostSecondaryInstitute"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_PostSecondaryInstitute> ecer_PostSecondaryInstituteSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_PostSecondaryInstitute>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_PreviousAddress"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_PreviousAddress> ecer_PreviousAddressSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_PreviousAddress>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_PreviousName"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_PreviousName> ecer_PreviousNameSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_PreviousName>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_ProfessionalDevelopment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_ProfessionalDevelopment> ecer_ProfessionalDevelopmentSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_ProfessionalDevelopment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Program"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Program> ecer_ProgramSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Program>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_Transcript"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_Transcript> ecer_TranscriptSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_Transcript>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_WorkExperienceAssessment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_WorkExperienceAssessment> ecer_WorkExperienceAssessmentSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_WorkExperienceAssessment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ECER.Utilities.DataverseSdk.Model.ecer_WorkExperienceRef"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ECER.Utilities.DataverseSdk.Model.ecer_WorkExperienceRef> ecer_WorkExperienceRefSet
		{
			get
			{
				return this.CreateQuery<ECER.Utilities.DataverseSdk.Model.ecer_WorkExperienceRef>();
			}
		}
	}
}
#pragma warning restore CS1591
