import { error } from "console";

let clientArray = [
  {
    clientId: "childcare-ecer",
    name: "ECER Portal Client",
    description: "",
    rootUrl: "",
    adminUrl: "",
    baseUrl: "https://myeceregistry.gov.bc.ca",
    surrogateAuthRequired: false,
    enabled: true,
    alwaysDisplayInConsole: false,
    clientAuthenticatorType: "client-secret",
    redirectUris: [
      "",
      "https://www.myeceregistry.gov.bc.ca/*",
      "https://myeceregistry.gov.bc.ca/*",
    ],
    webOrigins: ["+"],
    notBefore: 0,
    bearerOnly: false,
    consentRequired: false,
    standardFlowEnabled: true,
    implicitFlowEnabled: false,
    directAccessGrantsEnabled: true,
    serviceAccountsEnabled: false,
    publicClient: true,
    frontchannelLogout: false,
    protocol: "openid-connect",
    attributes: {
      "saml.multivalued.roles": "false",
      "saml.force.post.binding": "false",
      "frontchannel.logout.session.required": "false",
      "post.logout.redirect.uris": "+",
      "oauth2.device.authorization.grant.enabled": "false",
      "backchannel.logout.revoke.offline.tokens": "false",
      "saml.server.signature.keyinfo.ext": "false",
      "use.refresh.tokens": "true",
      realm_client: "false",
      "oidc.ciba.grant.enabled": "false",
      "backchannel.logout.session.required": "true",
      "client_credentials.use_refresh_token": "false",
      "saml.client.signature": "false",
      "require.pushed.authorization.requests": "false",
      "saml.allow.ecp.flow": "false",
      "saml.assertion.signature": "false",
      "id.token.as.detached.signature": "false",
      "saml.encrypt": "false",
      "saml.server.signature": "false",
      "exclude.session.state.from.auth.response": "false",
      "saml.artifact.binding": "false",
      "client.use.lightweight.access.token.enabled": "false",
      saml_force_name_id_format: "false",
      "tls.client.certificate.bound.access.tokens": "false",
      "acr.loa.map": "{}",
      "saml.authnstatement": "false",
      "display.on.consent.screen": "false",
      "token.response.type.bearer.lower-case": "false",
      "saml.onetimeuse.condition": "false",
    },
    authenticationFlowBindingOverrides: {},
    fullScopeAllowed: true,
    nodeReRegistrationTimeout: -1,
    protocolMappers: [
      {
        name: "identity_provider",
        protocol: "openid-connect",
        protocolMapper: "oidc-usermodel-attribute-mapper",
        consentRequired: false,
        config: {
          "user.attribute": "identity_provider",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "identity_provider",
          "jsonType.label": "String",
          "userinfo.token.claim": "false",
        },
      },
      {
        name: "audience",
        protocol: "openid-connect",
        protocolMapper: "oidc-audience-mapper",
        consentRequired: false,
        config: {
          "included.client.audience": "childcare-ecer",
          "introspection.token.claim": "true",
          "included.custom.audience": "aud",
          "userinfo.token.claim": "false",
          "id.token.claim": "false",
          "lightweight.claim": "false",
          "access.token.claim": "true",
        },
      },
      {
        name: "sub",
        protocol: "openid-connect",
        protocolMapper: "oidc-usermodel-attribute-mapper",
        consentRequired: false,
        config: {
          "user.attribute": "sub",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "sub",
          "jsonType.label": "String",
          "userinfo.token.claim": "true",
        },
      },
    ],
    defaultClientScopes: ["address", "profile", "basic", "email"],
    optionalClientScopes: [],
    access: {
      view: true,
      configure: true,
      manage: true,
    },
  },
  {
    clientId: "childcare-ecer-api",
    name: "Dataverse API User",
    description: "",
    rootUrl: "",
    adminUrl: "",
    baseUrl: "",
    surrogateAuthRequired: false,
    enabled: true,
    alwaysDisplayInConsole: false,
    clientAuthenticatorType: "client-secret",
    redirectUris: ["*"],
    webOrigins: [],
    notBefore: 0,
    bearerOnly: false,
    consentRequired: false,
    standardFlowEnabled: false,
    implicitFlowEnabled: false,
    directAccessGrantsEnabled: false,
    serviceAccountsEnabled: true,
    publicClient: false,
    frontchannelLogout: false,
    protocol: "openid-connect",
    attributes: {
      "saml.multivalued.roles": "false",
      "saml.force.post.binding": "false",
      "frontchannel.logout.session.required": "false",
      "post.logout.redirect.uris": "+",
      "oauth2.device.authorization.grant.enabled": "false",
      "backchannel.logout.revoke.offline.tokens": "false",
      "saml.server.signature.keyinfo.ext": "false",
      "use.refresh.tokens": "true",
      realm_client: "false",
      "oidc.ciba.grant.enabled": "false",
      "backchannel.logout.session.required": "true",
      "client_credentials.use_refresh_token": "false",
      "saml.client.signature": "false",
      "require.pushed.authorization.requests": "false",
      "saml.allow.ecp.flow": "false",
      "saml.assertion.signature": "false",
      "id.token.as.detached.signature": "false",
      "saml.encrypt": "false",
      "saml.server.signature": "false",
      "exclude.session.state.from.auth.response": "false",
      "saml.artifact.binding": "false",
      saml_force_name_id_format: "false",
      "tls.client.certificate.bound.access.tokens": "false",
      "acr.loa.map": "{}",
      "saml.authnstatement": "false",
      "display.on.consent.screen": "false",
      "token.response.type.bearer.lower-case": "false",
      "saml.onetimeuse.condition": "false",
    },
    authenticationFlowBindingOverrides: {},
    fullScopeAllowed: true,
    nodeReRegistrationTimeout: -1,
    protocolMappers: [
      {
        name: "audience",
        protocol: "openid-connect",
        protocolMapper: "oidc-audience-mapper",
        consentRequired: false,
        config: {
          "included.client.audience": "childcare-ecer-api",
          "id.token.claim": "false",
          "lightweight.claim": "false",
          "introspection.token.claim": "true",
          "access.token.claim": "true",
          "userinfo.token.claim": "false",
        },
      },
      {
        name: "Client ID",
        protocol: "openid-connect",
        protocolMapper: "oidc-usersessionmodel-note-mapper",
        consentRequired: false,
        config: {
          "user.session.note": "clientId",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "clientId",
          "jsonType.label": "String",
          "userinfo.token.claim": "true",
        },
      },
      {
        name: "Client IP Address",
        protocol: "openid-connect",
        protocolMapper: "oidc-usersessionmodel-note-mapper",
        consentRequired: false,
        config: {
          "user.session.note": "clientAddress",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "clientAddress",
          "jsonType.label": "String",
          "userinfo.token.claim": "true",
        },
      },
      {
        name: "Client Host",
        protocol: "openid-connect",
        protocolMapper: "oidc-usersessionmodel-note-mapper",
        consentRequired: false,
        config: {
          "user.session.note": "clientHost",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "clientHost",
          "jsonType.label": "String",
          "userinfo.token.claim": "true",
        },
      },
    ],
    defaultClientScopes: ["basic"],
    optionalClientScopes: [],
    access: {
      view: true,
      configure: true,
      manage: true,
    },
  },
  {
    clientId: "childcare-ecer-ew",
    name: "EW API User",
    description: "",
    rootUrl: "",
    adminUrl: "",
    baseUrl: "",
    surrogateAuthRequired: false,
    enabled: true,
    alwaysDisplayInConsole: false,
    clientAuthenticatorType: "client-secret",
    redirectUris: ["/*"],
    webOrigins: ["/*"],
    notBefore: 0,
    bearerOnly: false,
    consentRequired: false,
    standardFlowEnabled: false,
    implicitFlowEnabled: false,
    directAccessGrantsEnabled: false,
    serviceAccountsEnabled: true,
    publicClient: false,
    frontchannelLogout: true,
    protocol: "openid-connect",
    attributes: {
      realm_client: "false",
      "oidc.ciba.grant.enabled": "false",
      "backchannel.logout.session.required": "true",
      "oauth2.device.authorization.grant.enabled": "false",
      "display.on.consent.screen": "false",
      "backchannel.logout.revoke.offline.tokens": "false",
    },
    authenticationFlowBindingOverrides: {},
    fullScopeAllowed: true,
    nodeReRegistrationTimeout: -1,
    protocolMappers: [
      {
        name: "Client IP Address",
        protocol: "openid-connect",
        protocolMapper: "oidc-usersessionmodel-note-mapper",
        consentRequired: false,
        config: {
          "user.session.note": "clientAddress",
          "introspection.token.claim": "true",
          "userinfo.token.claim": "true",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "clientAddress",
          "jsonType.label": "String",
        },
      },
      {
        name: "Client ID",
        protocol: "openid-connect",
        protocolMapper: "oidc-usersessionmodel-note-mapper",
        consentRequired: false,
        config: {
          "user.session.note": "client_id",
          "introspection.token.claim": "true",
          "userinfo.token.claim": "true",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "client_id",
          "jsonType.label": "String",
        },
      },
      {
        name: "Client Host",
        protocol: "openid-connect",
        protocolMapper: "oidc-usersessionmodel-note-mapper",
        consentRequired: false,
        config: {
          "user.session.note": "clientHost",
          "introspection.token.claim": "true",
          "userinfo.token.claim": "true",
          "id.token.claim": "true",
          "access.token.claim": "true",
          "claim.name": "clientHost",
          "jsonType.label": "String",
        },
      },
      {
        name: "audience",
        protocol: "openid-connect",
        protocolMapper: "oidc-audience-mapper",
        consentRequired: false,
        config: {
          "included.client.audience": "childcare-ecer-ew",
          "id.token.claim": "false",
          "lightweight.claim": "false",
          "introspection.token.claim": "true",
          "access.token.claim": "true",
        },
      },
    ],
    defaultClientScopes: ["basic"],
    optionalClientScopes: [],
    access: {
      view: true,
      configure: true,
      manage: true,
    },
  },
  {
    clientId: "childcare-ecer-psp",
    name: "ECER PSP Portal Client",
    description: "client used for ECER psp portal login",
    rootUrl: "",
    adminUrl: "",
    baseUrl: "https://ecer-psp-portal.apps.silver.devops.gov.bc.ca",
    surrogateAuthRequired: false,
    enabled: true,
    alwaysDisplayInConsole: true,
    clientAuthenticatorType: "client-secret",
    redirectUris: ["https://ecer-psp-portal.apps.silver.devops.gov.bc.ca/*"],
    webOrigins: ["+"],
    notBefore: 0,
    bearerOnly: false,
    consentRequired: false,
    standardFlowEnabled: true,
    implicitFlowEnabled: false,
    directAccessGrantsEnabled: false,
    serviceAccountsEnabled: false,
    publicClient: true,
    frontchannelLogout: true,
    protocol: "openid-connect",
    attributes: {
      realm_client: "false",
      "oidc.ciba.grant.enabled": "false",
      "backchannel.logout.session.required": "true",
      "standard.token.exchange.enabled": "false",
      "post.logout.redirect.uris": "+",
      "frontchannel.logout.session.required": "true",
      "oauth2.device.authorization.grant.enabled": "false",
      "display.on.consent.screen": "false",
      "backchannel.logout.revoke.offline.tokens": "false",
    },
    authenticationFlowBindingOverrides: {},
    fullScopeAllowed: true,
    nodeReRegistrationTimeout: -1,
    protocolMappers: [
      {
        name: "bceid_business_guid",
        protocol: "openid-connect",
        protocolMapper: "oidc-usermodel-attribute-mapper",
        consentRequired: false,
        config: {
          "introspection.token.claim": "true",
          "userinfo.token.claim": "true",
          "user.attribute": "bceid_business_guid",
          "id.token.claim": "false",
          "lightweight.claim": "false",
          "access.token.claim": "false",
          "claim.name": "bceid_business_guid",
          "jsonType.label": "String",
        },
      },
      {
        name: "audience",
        protocol: "openid-connect",
        protocolMapper: "oidc-audience-mapper",
        consentRequired: false,
        config: {
          "included.client.audience": "childcare-ecer-psp-test",
          "id.token.claim": "false",
          "lightweight.claim": "false",
          "introspection.token.claim": "true",
          "access.token.claim": "true",
          "included.custom.audience": "aud",
        },
      },
      {
        name: "sub",
        protocol: "openid-connect",
        protocolMapper: "oidc-usermodel-attribute-mapper",
        consentRequired: false,
        config: {
          "introspection.token.claim": "true",
          "userinfo.token.claim": "true",
          "user.attribute": "sub",
          "id.token.claim": "true",
          "lightweight.claim": "false",
          "access.token.claim": "true",
          "claim.name": "sub",
          "jsonType.label": "String",
        },
      },
      {
        name: "identity_provider",
        protocol: "openid-connect",
        protocolMapper: "oidc-usermodel-attribute-mapper",
        consentRequired: false,
        config: {
          "introspection.token.claim": "true",
          "userinfo.token.claim": "false",
          "user.attribute": "identity_provider",
          "id.token.claim": "true",
          "lightweight.claim": "false",
          "access.token.claim": "true",
          "claim.name": "identity_provider",
          "jsonType.label": "String",
        },
      },
    ],
    defaultClientScopes: [
      "web-origins",
      "acr",
      "profile",
      "roles",
      "basic",
      "email",
    ],
    optionalClientScopes: [
      "address",
      "phone",
      "offline_access",
      "microprofile-jwt",
    ],
    access: {
      view: true,
      configure: true,
      manage: true,
    },
  },
];

function getProdClientJson(clientId) {
  let client = clientArray.find((client) => client.clientId === clientId);
  if (!client) {
    throw error(`Client ID ${clientId} not found in JSON data`);
  }
  return client;
}

export { getProdClientJson };
