apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-release-pipeline
spec:
  tasks:

    ## Promote dev ##
    - name: dev-registry-portal
      params:
        - name: sourceImage
          value: image-registry.apps.silver.devops.gov.bc.ca/b4566a-tools/registry-portal
        - name: sourceTag
          value: latest
        - name: destinationImage
          value: registry-portal
        - name: destinationTag
          value: dev
        - name: scheduled
          value: true
      taskRef:
        kind: Task
        name: tag-image-task
    - name: dev-api
      params:
        - name: sourceImage
          value: image-registry.apps.silver.devops.gov.bc.ca/b4566a-tools/ecc-ecer/api
        - name: sourceTag
          value: latest
        - name: destinationImage
          value: api
        - name: destinationTag
          value: dev
        - name: scheduled
          value: true
      taskRef:
        kind: Task
        name: tag-image-task
