apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: release-dev
  description: "Release to DEV"
spec:

  params:
    - name: srcImageTag
      description: "Source Image Tag"
      default: "master"
    {{- range $key, $value := .Values.images }}
    - name: promote-{{ $key }}
      description: "Promote {{ $key }}"
      default: "true"
    {{- end }}

  tasks:    
    {{- range $key, $value := .Values.images }}
    - name: promote-{{ $key }}
      when:
        - input: "$(params.promote-{{ $key }})"
          operator: in
          values: ["true"]
      params:
        - name: sourceImage
          value: {{ base $value.image }}
        - name: sourceTag
          value: $(params.srcImageTag)
        - name: destinationImage
          value: {{ base $value.image }}
        - name: destinationTag
          value: dev
        - name: alias
          value: true
      taskRef:
        kind: Task
        name: tag-image-task
    {{- end }}
