kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-pullers
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b4566a-dev
  - kind: ServiceAccount
    name: default
    namespace: b4566a-test
  - kind: ServiceAccount
    name: default
    namespace: b4566a-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
