apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: prod-release-pipeline
spec:
  tasks:

   ## Promote test to prod ##
    - name: prod-registry-portal
      params:
        - name: imageName
          value: registry-portal
        - name: fromTag
          value: test
        - name: toTag
          value: prod
      taskRef:
        kind: Task
        name: promote-image-task