apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: release-test
  description: "Release DEV to TEST"

spec:
  tasks:
    {{- range $key, $value := .Values.images }}
    - name: promote-{{ $key }}
      params:
        - name: imageName
          value: {{ base $value.image }}
        - name: fromTag
          value: dev
        - name: toTag
          value: test
      taskRef:
        kind: Task
        name: promote-image-task
    {{- end }}
