apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: release-uat
  description: "Release TEST to UAT"

spec:
  tasks:
    {{- range $key, $value := .Values.images }}
    - name: promote-{{ $key }}
      params:
        - name: imageName
          value: {{ base $value.image }}
        - name: fromTag
          value: test
        - name: toTag
          value: uat
      taskRef:
        kind: Task
        name: promote-image-task
    {{- end }}
