#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECER.Utilities.DataverseSdk.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ecer/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ecer_ECERWorkExperienceReferenceVerification")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class ecer_ECERWorkExperienceReferenceVerificationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Description
		{
			get
			{
				if (this.Parameters.Contains("Description"))
				{
					return ((string)(this.Parameters["Description"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Description"] = value;
			}
		}
		
		public string ReferrerGUID
		{
			get
			{
				if (this.Parameters.Contains("ReferrerGUID"))
				{
					return ((string)(this.Parameters["ReferrerGUID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ReferrerGUID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ecer_ECERWorkExperienceReferenceVerificationRequest()
		{
			this.RequestName = "ecer_ECERWorkExperienceReferenceVerification";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ecer/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ecer_ECERWorkExperienceReferenceVerification")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class ecer_ECERWorkExperienceReferenceVerificationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ecer_ECERWorkExperienceReferenceVerificationResponse()
		{
		}
	}
}
#pragma warning restore CS1591
