#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECER.Utilities.DataverseSdk.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum ecer_InvestigationDocumentTypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CarePlan = 621870002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailTextorIMCorrespondence = 621870005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FacilityPolicyandorProcedure = 621870004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HealthAuthorityReport = 621870000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Images = 621870009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 621870010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerformanceEvaluationbyEmployer = 621870006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PoliceRCMPReport = 621870001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReferenceChecks = 621870003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SurvellanceorCameraFootage = 621870008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WrittenWitnessAccount = 621870007,
	}
}
#pragma warning restore CS1591
