#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECER.Utilities.DataverseSdk.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum ecer_ApplicationTypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChangeofInformation = 621870002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LaborMobility = 621870003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 621870000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Renewal = 621870001,
	}
}
#pragma warning restore CS1591
