#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECER.Utilities.DataverseSdk.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum ecer_PSIApplicationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AddOnlineorHybridDeliveryMethod = 621870002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CurriculumRevisionsatRecognizedInstitution = 621870004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NewBasicECEPostBasicProgram = 621870000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NewCampusatRecognizedPrivateInstitution = 621870003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SatelliteProgram = 621870001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkIntegratedLearningProgram = 621870005,
	}
}
#pragma warning restore CS1591
