export default {
  dashboard: {
    applyNowButton: 'button[id="btnApplyNow"]',
    renew: 'button[id="btnRenew"]',
  },
  navigationBar: {
    logOutLink: 'p[id="lnkLogOut"]',
    userNameButton: 'button[id="btnUserName"]',
    toggleMenuButton: 'button[id="btnToggleMenu"]',
  },
  certificationType: {
    eceAssistantRadio: 'input[value="EceAssistant"]',
    eceFiveYearRadio: 'input[value="FiveYears"]',
    eceOneYearRadio: 'input[value="OneYear"]',
    continueButton: 'button[id="btnContinue"]',
    iteCheckBox: 'input[value="Ite"]',
    sneCheckBox: 'input[value="Sne"]',
  },
  applicationRequirements: {
    applyNowButton: 'button[id="btnApplyNow"]',
  },
  declaration: {
    declarationCheckbox: 'input[id="chkDeclaration"]',
    continueButton: 'button[id="btnContinue"]',
  },
  applicationWizard: {
    saveAndContinueButton: 'button[id="btnSaveAndContinue"]',
    submitApplicationButton: 'button[id="btnSubmitApplication"]',
  },
  applicationWizardHeader: {
    saveAndExitButton: 'button[id="btnSaveAndExit"]',
  },
  education: {
    addEducationButton: 'button[id="btnAddEducation"]',
    transcriptStatusRadioDiv: 'div[aria-describedby="radioTranscriptStatus-messages"]',
    programNameInput: 'input[id="txtProgramName"]',
    programStartDateInput: 'input[id="txtProgramStartDate"]',
    programEndDateInput: 'input[id="txtProgramEndDate"]',
    provinceDropDownList: 'input[id="ddlProvince"]',
    postSecondaryInstitutionDropDownList: 'input[id="ddlPostSecondaryInstitution"]',
    institutionNameInput: 'input[id="txtInstitutionName"]',
    studentIDInput: 'input[id="txtStudentID"]',
    nameOnTranscriptRadioDiv: 'div[aria-describedby="radioNameOnTranscript-messages"]',
    saveEducationButton: 'button[id="btnSaveEducation"]',
  },
  characterReference: {
    lastNameInput: 'input[id="txtReferenceLastName"]',
    firstNameInput: 'input[id="txtReferenceFirstName"]',
    emailInput: 'input[id="txtReferenceEmail"]',
    phoneNumberInput: 'input[id="txtReferencePhoneNumber"]',
  },
  workExperienceReference: {
    addReferenceButton: 'button[id="btnAddWorkExperienceReference"]',
    lastNameInput: 'input[id="txtWorkReferenceLastName"]',
    firstNameInput: 'input[id="txtWorkReferenceFirstName"]',
    emailInput: 'input[id="txtWorkReferenceEmail"]',
    phoneNumberInput: 'input[id="txtWorkReferencePhoneNumber"]',
    hoursInput: 'input[id="txtWorkReferenceHours"]',
    saveReferenceButton: 'button[id="btnSaveWorkReference"]',
  },
  professionalDevelopment: {
    addCourseOrWorkshop: 'button span.v-btn__content',
    courseNameInput: 'input[id="txtCourseName"]',
    howManyHours: 'input[id="txtNumberOfHours"]',
    nameOfPlace: 'input[id="txtOrganizationName"]',
    phoneNoOfInstructorCheckBox: 'input[id="chkInstructorPhoneNumber"]',
    nameOfInstructor: 'input[id="txtInstructorName"]',
    PhoneNoOfInstructor: 'input[id="txtOrganizationPhoneNumber"]',
    saveCourseOrWorkshop: 'button[id="btnSaveProfessionalDevelopment"]',
    courseStartDateInput: 'input[id="txtCourseStartDate"]',
    courseEndDateInput: 'input[id="txtCourseEndDate"]',
    renewalInformationcheck: 'input[value="IliveandworkinacommunitywithoutothercertifiedECEs"]'
  },
  datePicker: {
    monthDiv: "div.v-date-picker-month",
    monthControlsDiv: "div.v-date-picker-controls__month",
    controlsDiv: "div.v-date-picker-controls",
    prevMonthButton: 'button[data-testid="prev-month"]',
  },
  applicationPreview: {
    certificationType: 'p[id="certificationType"]',
    educationCountry: 'p[id="educationCountry"]',
    educationProvince: 'p[id="educationProvince"]',
    characterReferenceFirstName: 'p[id="characterReferenceFirstName"]',
    characterReferenceLastName: 'p[id="characterReferenceLastName"]',
    characterReferenceEmail: 'p[id="characterReferenceEmail"]',
    workReferenceEmail: 'p[id="workReferenceEmail"]',
    workReferenceName: 'h4[id="workReferenceName"]',
  },
  applicationSubmitted: {
    pageTitle: 'h1[id="titleApplicationSubmitted"]',
    applicationSummaryButton: 'button[id="btnApplicationSummary"]',
  },
  elementType: {
    radio: 'input[type="radio"]',
    input: "input",
    body: "body",
    button: "button",
  },
};
