services:
  registry-portal:
    image: registry-portal
    build:
      context: .
      dockerfile: registry-portal.Dockerfile
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - "5121:8080"
    depends_on:
      - redis

  api:
    image: api
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - "5051:8080"
    depends_on:
      - redis
     
  redis:
    image: redis:7
    ports:
      - "6379:6379"
