#!/usr/bin/env sh

set -e

cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client" && npm run validate-colors
cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.PSPPortal/ecer.clients.pspportal.client" && npm run validate-colors

cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client" && npm run format
cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.PSPPortal/ecer.clients.pspportal.client" && npm run format
