#!/usr/bin/env sh

set -e

cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client" && npm run validate-colors
cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.PSPPortal/ecer.clients.pspportal.client" && npm run validate-colors

# Run format and check if it made changes
if ! (cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.RegistryPortal/ecer.clients.registryportal.client" && npm run format-check) || 
 ! (cd "$(git rev-parse --show-toplevel)/src/ECER.Clients.PSPPortal/ecer.clients.pspportal.client" && npm run format-check); then

# Check if formatting changed any files
  echo "❌ Code formatting changes detected!"
  echo "📝 Please format the files."
  echo "🔄 Please stage the formatted files and commit again:"
  echo "   git add ."
  echo "   git commit"
  exit 1
fi

echo "✅ All files are properly formatted!"
