name: docker-build-template

on:
  workflow_call:
    inputs:
      IMAGE_CONTEXT:
        required: true
        type: string
      IMAGE_FILE:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      REGISTRY:
        required: true
        type: string

    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}
          tags: |
            type=ref,enable=${{github.event.inputs.version == ''}},event=branch
            type=ref,event=pr
            type=raw,priority=900,enable=${{github.event.inputs.version != ''}},value=release-${{ github.event.inputs.version }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.IMAGE_CONTEXT }}
          build-args: |
            "VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
            "TIMESTAMP=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}"
            "COMMIT=${{ github.sha }}"
          file: ${{ inputs.IMAGE_FILE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Scan the repo with Trivy repo scanner
      # https://github.com/aquasecurity/trivy-action
      - name: Run Trivy vulnerability scanner in repo mode
        if: github.event_name == 'pull_request'
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "repo-trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results
        if: github.event_name == 'pull_request'
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: "repo-trivy-results.sarif"

      # Scan the image with Trivy repo scanner
      # https://github.com/aquasecurity/trivy-action
      - name: Run Trivy Scan on the created container
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: "sarif"
          output: "image-trivy-results.sarif"
        env:
          TRIVY_USERNAME: "${{ secrets.REGISTRY_USER }}"
          TRIVY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Upload Trivy scan results
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: "image-trivy-results.sarif"
