name: Promote to Dev

env:
  # 🖊️ EDIT your repository secrets to log into your OpenShift cluster and set up the context.
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
  OPENSHIFT_SERVER: ${{ vars.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.ECER_NAMESPACE_NO_ENV }}-tools
  APP_ENVIRONMENT_DESTINATION: "dev"

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      version:
        description: "Version ex. master, release-1.0.0 or release-1.0.1 .etc"
        default: "master"
        required: true

jobs:
  openshift-cd:
    name: Promote Image
    runs-on: ubuntu-22.04
    environment: dev

    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
      - name: Check User Input
        run: |
          echo SOURCE ${{github.event.inputs.version}}
          if [[ "${{github.event.inputs.version}}" == "master" ]] || [[ "${{github.event.inputs.version}}" == "release-"* ]]; then
            echo user input validated ${{github.event.inputs.version}}
          else
            echo ::error::input must be 'master' or 'release-*' your input was ${{github.event.inputs.version}}
            exit 1
          fi
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

        # https://github.com/redhat-actions/oc-login#readme
      - name: Tag in OpenShift
        run: |
          set -eux
          echo VERSION: ${{github.event.inputs.version}}
          # Login to OpenShift and select project
          oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
          oc project ${{ env.OPENSHIFT_NAMESPACE }}

          echo promoting ${{github.event.inputs.version}} imagestream to ${{env.APP_ENVIRONMENT_DESTINATION}}

          oc tag -n ${{env.OPENSHIFT_NAMESPACE}} --alias=true registry-portal:${{github.event.inputs.version}} registry-portal:${{env.APP_ENVIRONMENT_DESTINATION}}
          oc tag -n ${{env.OPENSHIFT_NAMESPACE}} --alias=true api:${{github.event.inputs.version}} api:${{env.APP_ENVIRONMENT_DESTINATION}}
          # oc tag -n ${{env.OPENSHIFT_NAMESPACE}} --alias=true psp-portal:${{github.event.inputs.version}} psp-portal:${{env.APP_ENVIRONMENT_DESTINATION}}

          # E2ETestData only exists in Dev and is used for automation testing, this will not exist in higher environments. 
          oc tag -n ${{env.OPENSHIFT_NAMESPACE}} --alias=true e2e-test-data:${{github.event.inputs.version}} e2e-test-data:${{env.APP_ENVIRONMENT_DESTINATION}}
