name: Integration tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the integration tests Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: src
          file: src/integration-tests.Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: local/integration-tests

      - name: Execute tests
        env:
          TEST_SECRETS: ${{ secrets.INTEGRATION_TESTS_SECRETS }}
        run: |
          # Copy the secrets file to the integration tests container
          echo "$TEST_SECRETS" > secrets.json
          
          # Run the integration tests Docker image
          docker run -v secrets.json:/src/secrets.json -e SECRETS_FILE_PATH=/src/secrets.json local/integration-tests
