name: Registry Portal Build
on:
  push:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/registry-portal-build.yml
      - .github/workflows/build-template.yml

  pull_request:
    branches: ["master"]
    paths:
      - src/**
      - .github/workflows/registry-portal-build.yml
      - .github/workflows/build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: src
      IMAGE_FILE: src/registry-portal.Dockerfile
      IMAGE_NAME: ${{ github.repository }}/registry-portal
      REGISTRY: ghcr.io      
    secrets:
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
