name: Registry Portal Build
on:
  workflow_dispatch:

  push:
    branches:
      - master
      - "release/**"
    paths:
      - src/**
      - "!src/ECER.Clients.Api/**"
      - "!src/ECER.Clients.E2ETestData/**"
      - "!src/ECER.Clients.PSPPortal/**"
      - "!src/api.Dockerfile"
      - "!src/e2e-test-data.Dockerfile"
      - "!src/psp-portal.Dockerfile"
      - .github/workflows/registry-portal-build.yml
      - .github/workflows/build-template.yml

  pull_request:
    paths:
      - src/**
      - "!src/ECER.Clients.Api/**"
      - "!src/ECER.Clients.E2ETestData/**"
      - "!src/ECER.Clients.PSPPortal/**"
      - "!src/api.Dockerfile"
      - "!src/e2e-test-data.Dockerfile"
      - "!src/psp-portal.Dockerfile"
      - .github/workflows/registry-portal-build.yml
      - .github/workflows/build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: src
      IMAGE_FILE: src/registry-portal.Dockerfile
      IMAGE_NAME: registry-portal
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
