name: Code scans
on:
  workflow_dispatch:
jobs:
  registry-portal-trivy-scan:
    uses: bcgov/pipeline-templates/.github/workflows/trivy-container.yaml@main
    with:
      IMAGE: ghcr.io/bcgov/ecc-ecer/registry-portal
      TAG: latest

  registry-portal-zap-owasp:
    uses: bcgov/pipeline-templates/.github/workflows/owasp-scan.yaml@main
    with:
      ZAP_SCAN_TYPE: "full" # Accepted values are base and full.
      ZAP_TARGET_URL: https://dev-ecer-registry-portal.apps.silver.devops.gov.bc.ca/
      ZAP_DURATION: "2"
      ZAP_MAX_DURATION: "5"
      ZAP_GCP_PUBLISH: false
      # ZAP_GCP_PROJECT: phronesis-310405 # Only required if ZAP_GCP_PUBLISH is TRUE
      # ZAP_GCP_BUCKET: "zap-scan-results" # Only required if ZAP_GCP_PUBLISH is TRUE
    # secrets:
    #   GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} # Only required if ZAP_GCP_PUBLISH is TRUE

  sonar-repo-scan:
    uses: bcgov/pipeline-templates/.github/workflows/sonar-scanner.yaml@main
    with:
      ORG: ci-testing
      PROJECT_KEY: bcgov-pipeline-templates
      URL: https://sonarcloud.io
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
