name: Code scans
on:
  workflow_dispatch:
jobs:

  trivy-scan:
    uses: bcgov/pipeline-templates/.github/workflows/trivy-container.yaml@main
    with:
      IMAGE: gregnrobinson/bcgov-nginx-demo
      TAG: latest

  # codeql-scan:
  #   uses: bcgov/pipeline-templates/.github/workflows/codeql.yaml@main

  # sonar-repo-scan:
  #   uses: bcgov/pipeline-templates/.github/workflows/sonar-scanner.yaml@main
  #   with:
  #     ORG: ci-testing
  #     PROJECT_KEY: bcgov-pipeline-templates
  #     URL: https://sonarcloud.io
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
