name: Trivy Scans
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - "release/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Scan Registry Portal
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ vars.DOCKER_REGISTRY }}/registry-portal:${{ steps.extract_branch.outputs.branch }}"
          format: "sarif"
          output: "registry-portal-trivy-results.sarif"
        env:
          TRIVY_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          TRIVY_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Scan API
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ vars.DOCKER_REGISTRY }}/api:${{ steps.extract_branch.outputs.branch }}"
          format: "sarif"
          output: "api-trivy-results.sarif"
        env:
          TRIVY_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          TRIVY_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "."
