name: ZAP Scans

on:
  schedule:
    - cron: '3 0 * * Mon'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  registry-portal-zap-scan:
      runs-on: ubuntu-latest
      steps:
      - name: UI
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://dev-ecer-registry-portal.apps.silver.devops.gov.bc.ca'
          artifact_name: 'registry_portal_ui_zap_scan'
          issue_title: 'registry_portal_ui_zap_scan'
      - name: API
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://dev-ecer-registry-portal.apps.silver.devops.gov.bc.ca/swagger/v1/swagger.json'
          artifact_name: 'registry_portal_api_zap_scan'
          issue_title: 'registry_portal_api_zap_scan'

  api-zap-scan:
      runs-on: ubuntu-latest
      steps:
      - name: API
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://dev-ecer-api.apps.silver.devops.gov.bc.ca/swagger/v1/swagger.json'
          artifact_name: 'api_zap_scan'
          issue_title: 'api_zap_scan'
